#!/bin/bash
do_run=1 # Execute(evaluate) the commands
#do_run=0 # Don't evaluate any commands
#do_echo=1 # Echo the commands
do_echo=0 # Don't echo any commands
#
echo ""
solfile="./contract.sol"
contractName="Contract"
if [ "$#" -ge 1 ]; then
  solfile=$1
fi

if [ "$#" -ge 2 ]; then
  contractName=$2
fi

echo "Generating for "$solfile" contract : "$contractName

# solc --pretty-json --combined-json opcodes,srcmap ./zombiefactory.sol > outbin/out.json ; cat outbin/out.json | jq '.contracts | ."./zombiefactory.sol:ZombieFactory" '

echo ""
echo "Compiling..."
cmd='solc --pretty-json --combined-json opcodes,srcmap ./zombiefactory.sol > outbin/out.json ; cat outbin/out.json | jq '"'"'.contracts | ."./zombiefactory.sol:ZombieFactory" '"'"''
if [ $do_echo -eq 1 ]; then echo $cmd; fi
if [ $do_run -eq 1 ]; then eval $cmd; fi


